language: csharp
solution: JabbR-Core.sln

before_install:
    - curl https://raw.githubusercontent.com/dotnet/cli/c0c07ed959cc923cee91d0a2230dee7c701b7baa/scripts/obtain/dotnet-install.sh -o dotnet-install.sh
    - chmod a+rwx dotnet-install.sh
    - ls -al 
    - cat src/JabbR-Core/JabbR-Core.xproj    
script:
    - sudo ./dotnet-install.sh
    - xbuild JabbR-Core.sln
    - dotnet --version
    - dotnet restore
    - dotnet run -p src/JabbR-Core/