language: csharp
solution: JabbR-Core.sln

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          dotnet: 1.0.0-preview2-003121 
addons:
    # for just unit tests this isn't necessary
    # username and access key stored in env variables on Travis server
    sauce_connect: true
script:
    - dotnet --info
    - dotnet --version

    - cd src/JabbR-Core
    - dotnet restore

    - cd ../../test/JabbR-Core.Tests/
    # This builds JabbR-Core and JabbR-Core.Tests
    - dotnet restore
    - dotnet build

    # Run test suite
    - dotnet test

    # Open the server and let Sauce Labs connect
    # - cd ../../src/JabbR-Core/
    # - dotnet run