language: csharp
solution: JabbR-Core.sln

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          dotnet: 1.0.0-preview2-003121 
        - os: osx
          osx_image: xcode7.2
          dotnet: 1.0.0-preview2-003121 
addons:
    # username and access key stored in env variables on Travis server
    sauce_connect: true
script:
    - dotnet --info
    - dotnet --version

    - cd test/JabbR-Core.Tests/
    # This builds JabbR-Core and JabbR-Core.Tests
    - dotnet build

    # Run test suite
    - dotnet test